//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REGISTROASISTENCIA
    {
        public TBL_REGISTROASISTENCIA()
        {
            this.TBL_REGISTROFUNCIONARIO = new HashSet<TBL_REGISTROFUNCIONARIO>();
        }
    
        public decimal ID_REGISTRO { get; set; }
        public System.DateTime FH_INGRESO { get; set; }
        public System.DateTime FH_SALIDA { get; set; }
    
        public virtual ICollection<TBL_REGISTROFUNCIONARIO> TBL_REGISTROFUNCIONARIO { get; set; }
    }
}
