//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ESTADOSOLICITUDPERMISO
    {
        public decimal ID_ESTADO { get; set; }
        public decimal ID_SOLICITUDPERMISO { get; set; }
        public System.DateTime FH_ESTADO { get; set; }
        public decimal RESPONSABLE_ID { get; set; }
    
        public virtual TBL_ESTADO TBL_ESTADO { get; set; }
        public virtual TBL_SOLICITUDPERMISO TBL_SOLICITUDPERMISO { get; set; }
    }
}
