//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public TBL_USUARIO()
        {
            this.TBL_AUTENTIFICACION = new HashSet<TBL_AUTENTIFICACION>();
            this.TBL_PERMISOUSUARIO = new HashSet<TBL_PERMISOUSUARIO>();
            this.TBL_SOLICITUDPERMISO = new HashSet<TBL_SOLICITUDPERMISO>();
            this.TBL_ROL1 = new HashSet<TBL_ROL>();
            this.TBL_MODULO = new HashSet<TBL_MODULO>();
        }
    
        public decimal RUT_USUARIO { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string TEL_PARTICULAR { get; set; }
        public string DIR_PARTICULAR { get; set; }
        public string TEL_INSTITUCIONAL { get; set; }
        public string PASSWORD { get; set; }
        public decimal ID_UNIDAD_INTERNA { get; set; }
        public string EMAIL { get; set; }
        public string CARGO { get; set; }
        public Nullable<decimal> ID_ROL { get; set; }
    
        public virtual ICollection<TBL_AUTENTIFICACION> TBL_AUTENTIFICACION { get; set; }
        public virtual ICollection<TBL_PERMISOUSUARIO> TBL_PERMISOUSUARIO { get; set; }
        public virtual TBL_ROL TBL_ROL { get; set; }
        public virtual ICollection<TBL_SOLICITUDPERMISO> TBL_SOLICITUDPERMISO { get; set; }
        public virtual TBL_UNIDADINTERNA TBL_UNIDADINTERNA { get; set; }
        public virtual ICollection<TBL_ROL> TBL_ROL1 { get; set; }
        public virtual ICollection<TBL_MODULO> TBL_MODULO { get; set; }
    }
}
