//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REG_ERRORES
    {
        public int NUMERO_ERROR { get; set; }
        public string NOMBRESUBPROGRAMA { get; set; }
        public string NUMEROYMENSAJEDEERROR { get; set; }
        public Nullable<System.DateTime> FECHAHORAERROR { get; set; }
    }
}
