//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROL
    {
        public TBL_ROL()
        {
            this.TBL_USUARIO = new HashSet<TBL_USUARIO>();
            this.TBL_USUARIO1 = new HashSet<TBL_USUARIO>();
        }
    
        public decimal ID_ROL { get; set; }
        public string NOMBRE_ROL { get; set; }
        public string DESC_ROL { get; set; }
    
        public virtual ICollection<TBL_USUARIO> TBL_USUARIO { get; set; }
        public virtual ICollection<TBL_USUARIO> TBL_USUARIO1 { get; set; }
    }
}
