//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REGISTROFUNCIONARIO
    {
        public decimal RUT_FUNCIONARIO { get; set; }
        public decimal ID_REGISTRO { get; set; }
    
        public virtual TBL_REGISTROASISTENCIA TBL_REGISTROASISTENCIA { get; set; }
    }
}
