//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SOLICITUDPERMISO
    {
        public TBL_SOLICITUDPERMISO()
        {
            this.TBL_ESTADOSOLICITUDPERMISO = new HashSet<TBL_ESTADOSOLICITUDPERMISO>();
        }
    
        public decimal ID_SOLICITUD { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN_SOL { get; set; }
        public Nullable<decimal> RUT_USUARIO { get; set; }
        public decimal MOTIVO { get; set; }
    
        public virtual ICollection<TBL_ESTADOSOLICITUDPERMISO> TBL_ESTADOSOLICITUDPERMISO { get; set; }
        public virtual TBL_PERMISO TBL_PERMISO { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
