//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERMISOUSUARIO
    {
        public decimal RUT_USUARIO { get; set; }
        public decimal ID_PERMISO { get; set; }
        public Nullable<decimal> DIAS_AUTORIZADOS { get; set; }
        public string COMENTARIOS { get; set; }
    
        public virtual TBL_PERMISO TBL_PERMISO { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
