//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.VS_Login {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsLocal/", ConfigurationName="VS_Login.VHWService")]
    public interface VHWService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getSituacionEmpleadoRequest", ReplyAction="http://wsLocal/VHWService/getSituacionEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.getSituacionEmpleadoResponse getSituacionEmpleado(DAL.VS_Login.getSituacionEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getSituacionEmpleadoRequest", ReplyAction="http://wsLocal/VHWService/getSituacionEmpleadoResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.getSituacionEmpleadoResponse> getSituacionEmpleadoAsync(DAL.VS_Login.getSituacionEmpleadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getResolucionAllMesAnteriorRequest", ReplyAction="http://wsLocal/VHWService/getResolucionAllMesAnteriorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.getResolucionAllMesAnteriorResponse getResolucionAllMesAnterior(DAL.VS_Login.getResolucionAllMesAnteriorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getResolucionAllMesAnteriorRequest", ReplyAction="http://wsLocal/VHWService/getResolucionAllMesAnteriorResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.getResolucionAllMesAnteriorResponse> getResolucionAllMesAnteriorAsync(DAL.VS_Login.getResolucionAllMesAnteriorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/AutenticateRequest", ReplyAction="http://wsLocal/VHWService/AutenticateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.AutenticateResponse Autenticate(DAL.VS_Login.AutenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/AutenticateRequest", ReplyAction="http://wsLocal/VHWService/AutenticateResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.AutenticateResponse> AutenticateAsync(DAL.VS_Login.AutenticateRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/validateDocRequest", ReplyAction="http://wsLocal/VHWService/validateDocResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.validateDocResponse validateDoc(DAL.VS_Login.validateDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/validateDocRequest", ReplyAction="http://wsLocal/VHWService/validateDocResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.validateDocResponse> validateDocAsync(DAL.VS_Login.validateDocRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getResolucionAllRequest", ReplyAction="http://wsLocal/VHWService/getResolucionAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.getResolucionAllResponse getResolucionAll(DAL.VS_Login.getResolucionAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getResolucionAllRequest", ReplyAction="http://wsLocal/VHWService/getResolucionAllResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.getResolucionAllResponse> getResolucionAllAsync(DAL.VS_Login.getResolucionAllRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getAntiguedadFunRequest", ReplyAction="http://wsLocal/VHWService/getAntiguedadFunResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.getAntiguedadFunResponse getAntiguedadFun(DAL.VS_Login.getAntiguedadFunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getAntiguedadFunRequest", ReplyAction="http://wsLocal/VHWService/getAntiguedadFunResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.getAntiguedadFunResponse> getAntiguedadFunAsync(DAL.VS_Login.getAntiguedadFunRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getAllByRutRequest", ReplyAction="http://wsLocal/VHWService/getAllByRutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.getAllByRutResponse getAllByRut(DAL.VS_Login.getAllByRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getAllByRutRequest", ReplyAction="http://wsLocal/VHWService/getAllByRutResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.getAllByRutResponse> getAllByRutAsync(DAL.VS_Login.getAllByRutRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/lstCantidadPermisoEstadoRequest", ReplyAction="http://wsLocal/VHWService/lstCantidadPermisoEstadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.lstCantidadPermisoEstadoResponse lstCantidadPermisoEstado(DAL.VS_Login.lstCantidadPermisoEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/lstCantidadPermisoEstadoRequest", ReplyAction="http://wsLocal/VHWService/lstCantidadPermisoEstadoResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.lstCantidadPermisoEstadoResponse> lstCantidadPermisoEstadoAsync(DAL.VS_Login.lstCantidadPermisoEstadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/lstCantidadPermisoEstadoUnidadRequest", ReplyAction="http://wsLocal/VHWService/lstCantidadPermisoEstadoUnidadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DAL.VS_Login.lstCantidadPermisoEstadoUnidadResponse lstCantidadPermisoEstadoUnidad(DAL.VS_Login.lstCantidadPermisoEstadoUnidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/lstCantidadPermisoEstadoUnidadRequest", ReplyAction="http://wsLocal/VHWService/lstCantidadPermisoEstadoUnidadResponse")]
        System.Threading.Tasks.Task<DAL.VS_Login.lstCantidadPermisoEstadoUnidadResponse> lstCantidadPermisoEstadoUnidadAsync(DAL.VS_Login.lstCantidadPermisoEstadoUnidadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSituacionEmpleado", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getSituacionEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rut;
        
        public getSituacionEmpleadoRequest() {
        }
        
        public getSituacionEmpleadoRequest(int rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSituacionEmpleadoResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getSituacionEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getSituacionEmpleadoResponse() {
        }
        
        public getSituacionEmpleadoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsLocal/")]
    public partial class permisoUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int diasAutField;
        
        private string estadoField;
        
        private string recursoLegalField;
        
        private int rutField;
        
        private int solicitudField;
        
        private string unidadInternaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int diasAut {
            get {
                return this.diasAutField;
            }
            set {
                this.diasAutField = value;
                this.RaisePropertyChanged("diasAut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string recursoLegal {
            get {
                return this.recursoLegalField;
            }
            set {
                this.recursoLegalField = value;
                this.RaisePropertyChanged("recursoLegal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int solicitud {
            get {
                return this.solicitudField;
            }
            set {
                this.solicitudField = value;
                this.RaisePropertyChanged("solicitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string unidadInterna {
            get {
                return this.unidadInternaField;
            }
            set {
                this.unidadInternaField = value;
                this.RaisePropertyChanged("unidadInterna");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsLocal/")]
    public partial class resumenCantidadPerEstado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private string recursoLegalField;
        
        private string unidadInternaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recursoLegal {
            get {
                return this.recursoLegalField;
            }
            set {
                this.recursoLegalField = value;
                this.RaisePropertyChanged("recursoLegal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string unidadInterna {
            get {
                return this.unidadInternaField;
            }
            set {
                this.unidadInternaField = value;
                this.RaisePropertyChanged("unidadInterna");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResolucionAllMesAnterior", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getResolucionAllMesAnteriorRequest {
        
        public getResolucionAllMesAnteriorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResolucionAllMesAnteriorResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getResolucionAllMesAnteriorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DAL.VS_Login.permisoUsuario[] @return;
        
        public getResolucionAllMesAnteriorResponse() {
        }
        
        public getResolucionAllMesAnteriorResponse(DAL.VS_Login.permisoUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Autenticate", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class AutenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public AutenticateRequest() {
        }
        
        public AutenticateRequest(int rut, string password) {
            this.rut = rut;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticateResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class AutenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AutenticateResponse() {
        }
        
        public AutenticateResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDoc", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class validateDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string num;
        
        public validateDocRequest() {
        }
        
        public validateDocRequest(string num) {
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDocResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class validateDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public validateDocResponse() {
        }
        
        public validateDocResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResolucionAll", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getResolucionAllRequest {
        
        public getResolucionAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResolucionAllResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getResolucionAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DAL.VS_Login.permisoUsuario[] @return;
        
        public getResolucionAllResponse() {
        }
        
        public getResolucionAllResponse(DAL.VS_Login.permisoUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAntiguedadFun", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getAntiguedadFunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rutFun;
        
        public getAntiguedadFunRequest() {
        }
        
        public getAntiguedadFunRequest(int rutFun) {
            this.rutFun = rutFun;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAntiguedadFunResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getAntiguedadFunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getAntiguedadFunResponse() {
        }
        
        public getAntiguedadFunResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllByRut", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getAllByRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rut;
        
        public getAllByRutRequest() {
        }
        
        public getAllByRutRequest(int rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllByRutResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getAllByRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DAL.VS_Login.permisoUsuario[] @return;
        
        public getAllByRutResponse() {
        }
        
        public getAllByRutResponse(DAL.VS_Login.permisoUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lstCantidadPermisoEstado", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class lstCantidadPermisoEstadoRequest {
        
        public lstCantidadPermisoEstadoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lstCantidadPermisoEstadoResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class lstCantidadPermisoEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DAL.VS_Login.resumenCantidadPerEstado[] @return;
        
        public lstCantidadPermisoEstadoResponse() {
        }
        
        public lstCantidadPermisoEstadoResponse(DAL.VS_Login.resumenCantidadPerEstado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lstCantidadPermisoEstadoUnidad", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class lstCantidadPermisoEstadoUnidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unidadInterna;
        
        public lstCantidadPermisoEstadoUnidadRequest() {
        }
        
        public lstCantidadPermisoEstadoUnidadRequest(string unidadInterna) {
            this.unidadInterna = unidadInterna;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lstCantidadPermisoEstadoUnidadResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class lstCantidadPermisoEstadoUnidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DAL.VS_Login.resumenCantidadPerEstado[] @return;
        
        public lstCantidadPermisoEstadoUnidadResponse() {
        }
        
        public lstCantidadPermisoEstadoUnidadResponse(DAL.VS_Login.resumenCantidadPerEstado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VHWServiceChannel : DAL.VS_Login.VHWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VHWServiceClient : System.ServiceModel.ClientBase<DAL.VS_Login.VHWService>, DAL.VS_Login.VHWService {
        
        public VHWServiceClient() {
        }
        
        public VHWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VHWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VHWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VHWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.getSituacionEmpleadoResponse DAL.VS_Login.VHWService.getSituacionEmpleado(DAL.VS_Login.getSituacionEmpleadoRequest request) {
            return base.Channel.getSituacionEmpleado(request);
        }
        
        public string getSituacionEmpleado(int rut) {
            DAL.VS_Login.getSituacionEmpleadoRequest inValue = new DAL.VS_Login.getSituacionEmpleadoRequest();
            inValue.rut = rut;
            DAL.VS_Login.getSituacionEmpleadoResponse retVal = ((DAL.VS_Login.VHWService)(this)).getSituacionEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.getSituacionEmpleadoResponse> DAL.VS_Login.VHWService.getSituacionEmpleadoAsync(DAL.VS_Login.getSituacionEmpleadoRequest request) {
            return base.Channel.getSituacionEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.getSituacionEmpleadoResponse> getSituacionEmpleadoAsync(int rut) {
            DAL.VS_Login.getSituacionEmpleadoRequest inValue = new DAL.VS_Login.getSituacionEmpleadoRequest();
            inValue.rut = rut;
            return ((DAL.VS_Login.VHWService)(this)).getSituacionEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.getResolucionAllMesAnteriorResponse DAL.VS_Login.VHWService.getResolucionAllMesAnterior(DAL.VS_Login.getResolucionAllMesAnteriorRequest request) {
            return base.Channel.getResolucionAllMesAnterior(request);
        }
        
        public DAL.VS_Login.permisoUsuario[] getResolucionAllMesAnterior() {
            DAL.VS_Login.getResolucionAllMesAnteriorRequest inValue = new DAL.VS_Login.getResolucionAllMesAnteriorRequest();
            DAL.VS_Login.getResolucionAllMesAnteriorResponse retVal = ((DAL.VS_Login.VHWService)(this)).getResolucionAllMesAnterior(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.getResolucionAllMesAnteriorResponse> DAL.VS_Login.VHWService.getResolucionAllMesAnteriorAsync(DAL.VS_Login.getResolucionAllMesAnteriorRequest request) {
            return base.Channel.getResolucionAllMesAnteriorAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.getResolucionAllMesAnteriorResponse> getResolucionAllMesAnteriorAsync() {
            DAL.VS_Login.getResolucionAllMesAnteriorRequest inValue = new DAL.VS_Login.getResolucionAllMesAnteriorRequest();
            return ((DAL.VS_Login.VHWService)(this)).getResolucionAllMesAnteriorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.AutenticateResponse DAL.VS_Login.VHWService.Autenticate(DAL.VS_Login.AutenticateRequest request) {
            return base.Channel.Autenticate(request);
        }
        
        public bool Autenticate(int rut, string password) {
            DAL.VS_Login.AutenticateRequest inValue = new DAL.VS_Login.AutenticateRequest();
            inValue.rut = rut;
            inValue.password = password;
            DAL.VS_Login.AutenticateResponse retVal = ((DAL.VS_Login.VHWService)(this)).Autenticate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.AutenticateResponse> DAL.VS_Login.VHWService.AutenticateAsync(DAL.VS_Login.AutenticateRequest request) {
            return base.Channel.AutenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.AutenticateResponse> AutenticateAsync(int rut, string password) {
            DAL.VS_Login.AutenticateRequest inValue = new DAL.VS_Login.AutenticateRequest();
            inValue.rut = rut;
            inValue.password = password;
            return ((DAL.VS_Login.VHWService)(this)).AutenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.validateDocResponse DAL.VS_Login.VHWService.validateDoc(DAL.VS_Login.validateDocRequest request) {
            return base.Channel.validateDoc(request);
        }
        
        public bool validateDoc(string num) {
            DAL.VS_Login.validateDocRequest inValue = new DAL.VS_Login.validateDocRequest();
            inValue.num = num;
            DAL.VS_Login.validateDocResponse retVal = ((DAL.VS_Login.VHWService)(this)).validateDoc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.validateDocResponse> DAL.VS_Login.VHWService.validateDocAsync(DAL.VS_Login.validateDocRequest request) {
            return base.Channel.validateDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.validateDocResponse> validateDocAsync(string num) {
            DAL.VS_Login.validateDocRequest inValue = new DAL.VS_Login.validateDocRequest();
            inValue.num = num;
            return ((DAL.VS_Login.VHWService)(this)).validateDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.getResolucionAllResponse DAL.VS_Login.VHWService.getResolucionAll(DAL.VS_Login.getResolucionAllRequest request) {
            return base.Channel.getResolucionAll(request);
        }
        
        public DAL.VS_Login.permisoUsuario[] getResolucionAll() {
            DAL.VS_Login.getResolucionAllRequest inValue = new DAL.VS_Login.getResolucionAllRequest();
            DAL.VS_Login.getResolucionAllResponse retVal = ((DAL.VS_Login.VHWService)(this)).getResolucionAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.getResolucionAllResponse> DAL.VS_Login.VHWService.getResolucionAllAsync(DAL.VS_Login.getResolucionAllRequest request) {
            return base.Channel.getResolucionAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.getResolucionAllResponse> getResolucionAllAsync() {
            DAL.VS_Login.getResolucionAllRequest inValue = new DAL.VS_Login.getResolucionAllRequest();
            return ((DAL.VS_Login.VHWService)(this)).getResolucionAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.getAntiguedadFunResponse DAL.VS_Login.VHWService.getAntiguedadFun(DAL.VS_Login.getAntiguedadFunRequest request) {
            return base.Channel.getAntiguedadFun(request);
        }
        
        public int getAntiguedadFun(int rutFun) {
            DAL.VS_Login.getAntiguedadFunRequest inValue = new DAL.VS_Login.getAntiguedadFunRequest();
            inValue.rutFun = rutFun;
            DAL.VS_Login.getAntiguedadFunResponse retVal = ((DAL.VS_Login.VHWService)(this)).getAntiguedadFun(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.getAntiguedadFunResponse> DAL.VS_Login.VHWService.getAntiguedadFunAsync(DAL.VS_Login.getAntiguedadFunRequest request) {
            return base.Channel.getAntiguedadFunAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.getAntiguedadFunResponse> getAntiguedadFunAsync(int rutFun) {
            DAL.VS_Login.getAntiguedadFunRequest inValue = new DAL.VS_Login.getAntiguedadFunRequest();
            inValue.rutFun = rutFun;
            return ((DAL.VS_Login.VHWService)(this)).getAntiguedadFunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.getAllByRutResponse DAL.VS_Login.VHWService.getAllByRut(DAL.VS_Login.getAllByRutRequest request) {
            return base.Channel.getAllByRut(request);
        }
        
        public DAL.VS_Login.permisoUsuario[] getAllByRut(int rut) {
            DAL.VS_Login.getAllByRutRequest inValue = new DAL.VS_Login.getAllByRutRequest();
            inValue.rut = rut;
            DAL.VS_Login.getAllByRutResponse retVal = ((DAL.VS_Login.VHWService)(this)).getAllByRut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.getAllByRutResponse> DAL.VS_Login.VHWService.getAllByRutAsync(DAL.VS_Login.getAllByRutRequest request) {
            return base.Channel.getAllByRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.getAllByRutResponse> getAllByRutAsync(int rut) {
            DAL.VS_Login.getAllByRutRequest inValue = new DAL.VS_Login.getAllByRutRequest();
            inValue.rut = rut;
            return ((DAL.VS_Login.VHWService)(this)).getAllByRutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.lstCantidadPermisoEstadoResponse DAL.VS_Login.VHWService.lstCantidadPermisoEstado(DAL.VS_Login.lstCantidadPermisoEstadoRequest request) {
            return base.Channel.lstCantidadPermisoEstado(request);
        }
        
        public DAL.VS_Login.resumenCantidadPerEstado[] lstCantidadPermisoEstado() {
            DAL.VS_Login.lstCantidadPermisoEstadoRequest inValue = new DAL.VS_Login.lstCantidadPermisoEstadoRequest();
            DAL.VS_Login.lstCantidadPermisoEstadoResponse retVal = ((DAL.VS_Login.VHWService)(this)).lstCantidadPermisoEstado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.lstCantidadPermisoEstadoResponse> DAL.VS_Login.VHWService.lstCantidadPermisoEstadoAsync(DAL.VS_Login.lstCantidadPermisoEstadoRequest request) {
            return base.Channel.lstCantidadPermisoEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.lstCantidadPermisoEstadoResponse> lstCantidadPermisoEstadoAsync() {
            DAL.VS_Login.lstCantidadPermisoEstadoRequest inValue = new DAL.VS_Login.lstCantidadPermisoEstadoRequest();
            return ((DAL.VS_Login.VHWService)(this)).lstCantidadPermisoEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DAL.VS_Login.lstCantidadPermisoEstadoUnidadResponse DAL.VS_Login.VHWService.lstCantidadPermisoEstadoUnidad(DAL.VS_Login.lstCantidadPermisoEstadoUnidadRequest request) {
            return base.Channel.lstCantidadPermisoEstadoUnidad(request);
        }
        
        public DAL.VS_Login.resumenCantidadPerEstado[] lstCantidadPermisoEstadoUnidad(string unidadInterna) {
            DAL.VS_Login.lstCantidadPermisoEstadoUnidadRequest inValue = new DAL.VS_Login.lstCantidadPermisoEstadoUnidadRequest();
            inValue.unidadInterna = unidadInterna;
            DAL.VS_Login.lstCantidadPermisoEstadoUnidadResponse retVal = ((DAL.VS_Login.VHWService)(this)).lstCantidadPermisoEstadoUnidad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DAL.VS_Login.lstCantidadPermisoEstadoUnidadResponse> DAL.VS_Login.VHWService.lstCantidadPermisoEstadoUnidadAsync(DAL.VS_Login.lstCantidadPermisoEstadoUnidadRequest request) {
            return base.Channel.lstCantidadPermisoEstadoUnidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DAL.VS_Login.lstCantidadPermisoEstadoUnidadResponse> lstCantidadPermisoEstadoUnidadAsync(string unidadInterna) {
            DAL.VS_Login.lstCantidadPermisoEstadoUnidadRequest inValue = new DAL.VS_Login.lstCantidadPermisoEstadoUnidadRequest();
            inValue.unidadInterna = unidadInterna;
            return ((DAL.VS_Login.VHWService)(this)).lstCantidadPermisoEstadoUnidadAsync(inValue);
        }
    }
}
