//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsLocal/", ConfigurationName="ServiceReference1.VHWService")]
    public interface VHWService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getSituacionEmpleadoRequest", ReplyAction="http://wsLocal/VHWService/getSituacionEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.getSituacionEmpleadoResponse getSituacionEmpleado(Presentacion.ServiceReference1.getSituacionEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getSituacionEmpleadoRequest", ReplyAction="http://wsLocal/VHWService/getSituacionEmpleadoResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getSituacionEmpleadoResponse> getSituacionEmpleadoAsync(Presentacion.ServiceReference1.getSituacionEmpleadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getResolucionAllMesAnteriorRequest", ReplyAction="http://wsLocal/VHWService/getResolucionAllMesAnteriorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.getResolucionAllMesAnteriorResponse getResolucionAllMesAnterior(Presentacion.ServiceReference1.getResolucionAllMesAnteriorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getResolucionAllMesAnteriorRequest", ReplyAction="http://wsLocal/VHWService/getResolucionAllMesAnteriorResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getResolucionAllMesAnteriorResponse> getResolucionAllMesAnteriorAsync(Presentacion.ServiceReference1.getResolucionAllMesAnteriorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/AutenticateRequest", ReplyAction="http://wsLocal/VHWService/AutenticateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.AutenticateResponse Autenticate(Presentacion.ServiceReference1.AutenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/AutenticateRequest", ReplyAction="http://wsLocal/VHWService/AutenticateResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.AutenticateResponse> AutenticateAsync(Presentacion.ServiceReference1.AutenticateRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/validateDocRequest", ReplyAction="http://wsLocal/VHWService/validateDocResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.validateDocResponse validateDoc(Presentacion.ServiceReference1.validateDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/validateDocRequest", ReplyAction="http://wsLocal/VHWService/validateDocResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.validateDocResponse> validateDocAsync(Presentacion.ServiceReference1.validateDocRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getResolucionAllRequest", ReplyAction="http://wsLocal/VHWService/getResolucionAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.getResolucionAllResponse getResolucionAll(Presentacion.ServiceReference1.getResolucionAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getResolucionAllRequest", ReplyAction="http://wsLocal/VHWService/getResolucionAllResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getResolucionAllResponse> getResolucionAllAsync(Presentacion.ServiceReference1.getResolucionAllRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getAntiguedadFunRequest", ReplyAction="http://wsLocal/VHWService/getAntiguedadFunResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.getAntiguedadFunResponse getAntiguedadFun(Presentacion.ServiceReference1.getAntiguedadFunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getAntiguedadFunRequest", ReplyAction="http://wsLocal/VHWService/getAntiguedadFunResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getAntiguedadFunResponse> getAntiguedadFunAsync(Presentacion.ServiceReference1.getAntiguedadFunRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getAllByRutRequest", ReplyAction="http://wsLocal/VHWService/getAllByRutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.getAllByRutResponse getAllByRut(Presentacion.ServiceReference1.getAllByRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/getAllByRutRequest", ReplyAction="http://wsLocal/VHWService/getAllByRutResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getAllByRutResponse> getAllByRutAsync(Presentacion.ServiceReference1.getAllByRutRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/lstCantidadPermisoEstadoRequest", ReplyAction="http://wsLocal/VHWService/lstCantidadPermisoEstadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.lstCantidadPermisoEstadoResponse lstCantidadPermisoEstado(Presentacion.ServiceReference1.lstCantidadPermisoEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/lstCantidadPermisoEstadoRequest", ReplyAction="http://wsLocal/VHWService/lstCantidadPermisoEstadoResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.lstCantidadPermisoEstadoResponse> lstCantidadPermisoEstadoAsync(Presentacion.ServiceReference1.lstCantidadPermisoEstadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/lstCantidadPermisoEstadoUnidadRequest", ReplyAction="http://wsLocal/VHWService/lstCantidadPermisoEstadoUnidadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadResponse lstCantidadPermisoEstadoUnidad(Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsLocal/VHWService/lstCantidadPermisoEstadoUnidadRequest", ReplyAction="http://wsLocal/VHWService/lstCantidadPermisoEstadoUnidadResponse")]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadResponse> lstCantidadPermisoEstadoUnidadAsync(Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSituacionEmpleado", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getSituacionEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rut;
        
        public getSituacionEmpleadoRequest() {
        }
        
        public getSituacionEmpleadoRequest(int rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSituacionEmpleadoResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getSituacionEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getSituacionEmpleadoResponse() {
        }
        
        public getSituacionEmpleadoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsLocal/")]
    public partial class permisoUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int diasAutField;
        
        private string estadoField;
        
        private string recursoLegalField;
        
        private int rutField;
        
        private int solicitudField;
        
        private string unidadInternaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int diasAut {
            get {
                return this.diasAutField;
            }
            set {
                this.diasAutField = value;
                this.RaisePropertyChanged("diasAut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string recursoLegal {
            get {
                return this.recursoLegalField;
            }
            set {
                this.recursoLegalField = value;
                this.RaisePropertyChanged("recursoLegal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int solicitud {
            get {
                return this.solicitudField;
            }
            set {
                this.solicitudField = value;
                this.RaisePropertyChanged("solicitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string unidadInterna {
            get {
                return this.unidadInternaField;
            }
            set {
                this.unidadInternaField = value;
                this.RaisePropertyChanged("unidadInterna");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsLocal/")]
    public partial class resumenCantidadPerEstado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private string recursoLegalField;
        
        private string unidadInternaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recursoLegal {
            get {
                return this.recursoLegalField;
            }
            set {
                this.recursoLegalField = value;
                this.RaisePropertyChanged("recursoLegal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string unidadInterna {
            get {
                return this.unidadInternaField;
            }
            set {
                this.unidadInternaField = value;
                this.RaisePropertyChanged("unidadInterna");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResolucionAllMesAnterior", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getResolucionAllMesAnteriorRequest {
        
        public getResolucionAllMesAnteriorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResolucionAllMesAnteriorResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getResolucionAllMesAnteriorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Presentacion.ServiceReference1.permisoUsuario[] @return;
        
        public getResolucionAllMesAnteriorResponse() {
        }
        
        public getResolucionAllMesAnteriorResponse(Presentacion.ServiceReference1.permisoUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Autenticate", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class AutenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public AutenticateRequest() {
        }
        
        public AutenticateRequest(int rut, string password) {
            this.rut = rut;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticateResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class AutenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AutenticateResponse() {
        }
        
        public AutenticateResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDoc", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class validateDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string num;
        
        public validateDocRequest() {
        }
        
        public validateDocRequest(string num) {
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDocResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class validateDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public validateDocResponse() {
        }
        
        public validateDocResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResolucionAll", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getResolucionAllRequest {
        
        public getResolucionAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResolucionAllResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getResolucionAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Presentacion.ServiceReference1.permisoUsuario[] @return;
        
        public getResolucionAllResponse() {
        }
        
        public getResolucionAllResponse(Presentacion.ServiceReference1.permisoUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAntiguedadFun", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getAntiguedadFunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rutFun;
        
        public getAntiguedadFunRequest() {
        }
        
        public getAntiguedadFunRequest(int rutFun) {
            this.rutFun = rutFun;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAntiguedadFunResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getAntiguedadFunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getAntiguedadFunResponse() {
        }
        
        public getAntiguedadFunResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllByRut", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getAllByRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rut;
        
        public getAllByRutRequest() {
        }
        
        public getAllByRutRequest(int rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllByRutResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class getAllByRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Presentacion.ServiceReference1.permisoUsuario[] @return;
        
        public getAllByRutResponse() {
        }
        
        public getAllByRutResponse(Presentacion.ServiceReference1.permisoUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lstCantidadPermisoEstado", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class lstCantidadPermisoEstadoRequest {
        
        public lstCantidadPermisoEstadoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lstCantidadPermisoEstadoResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class lstCantidadPermisoEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Presentacion.ServiceReference1.resumenCantidadPerEstado[] @return;
        
        public lstCantidadPermisoEstadoResponse() {
        }
        
        public lstCantidadPermisoEstadoResponse(Presentacion.ServiceReference1.resumenCantidadPerEstado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lstCantidadPermisoEstadoUnidad", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class lstCantidadPermisoEstadoUnidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unidadInterna;
        
        public lstCantidadPermisoEstadoUnidadRequest() {
        }
        
        public lstCantidadPermisoEstadoUnidadRequest(string unidadInterna) {
            this.unidadInterna = unidadInterna;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lstCantidadPermisoEstadoUnidadResponse", WrapperNamespace="http://wsLocal/", IsWrapped=true)]
    public partial class lstCantidadPermisoEstadoUnidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsLocal/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Presentacion.ServiceReference1.resumenCantidadPerEstado[] @return;
        
        public lstCantidadPermisoEstadoUnidadResponse() {
        }
        
        public lstCantidadPermisoEstadoUnidadResponse(Presentacion.ServiceReference1.resumenCantidadPerEstado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VHWServiceChannel : Presentacion.ServiceReference1.VHWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VHWServiceClient : System.ServiceModel.ClientBase<Presentacion.ServiceReference1.VHWService>, Presentacion.ServiceReference1.VHWService {
        
        public VHWServiceClient() {
        }
        
        public VHWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VHWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VHWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VHWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.getSituacionEmpleadoResponse Presentacion.ServiceReference1.VHWService.getSituacionEmpleado(Presentacion.ServiceReference1.getSituacionEmpleadoRequest request) {
            return base.Channel.getSituacionEmpleado(request);
        }
        
        public string getSituacionEmpleado(int rut) {
            Presentacion.ServiceReference1.getSituacionEmpleadoRequest inValue = new Presentacion.ServiceReference1.getSituacionEmpleadoRequest();
            inValue.rut = rut;
            Presentacion.ServiceReference1.getSituacionEmpleadoResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).getSituacionEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getSituacionEmpleadoResponse> Presentacion.ServiceReference1.VHWService.getSituacionEmpleadoAsync(Presentacion.ServiceReference1.getSituacionEmpleadoRequest request) {
            return base.Channel.getSituacionEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.getSituacionEmpleadoResponse> getSituacionEmpleadoAsync(int rut) {
            Presentacion.ServiceReference1.getSituacionEmpleadoRequest inValue = new Presentacion.ServiceReference1.getSituacionEmpleadoRequest();
            inValue.rut = rut;
            return ((Presentacion.ServiceReference1.VHWService)(this)).getSituacionEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.getResolucionAllMesAnteriorResponse Presentacion.ServiceReference1.VHWService.getResolucionAllMesAnterior(Presentacion.ServiceReference1.getResolucionAllMesAnteriorRequest request) {
            return base.Channel.getResolucionAllMesAnterior(request);
        }
        
        public Presentacion.ServiceReference1.permisoUsuario[] getResolucionAllMesAnterior() {
            Presentacion.ServiceReference1.getResolucionAllMesAnteriorRequest inValue = new Presentacion.ServiceReference1.getResolucionAllMesAnteriorRequest();
            Presentacion.ServiceReference1.getResolucionAllMesAnteriorResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).getResolucionAllMesAnterior(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getResolucionAllMesAnteriorResponse> Presentacion.ServiceReference1.VHWService.getResolucionAllMesAnteriorAsync(Presentacion.ServiceReference1.getResolucionAllMesAnteriorRequest request) {
            return base.Channel.getResolucionAllMesAnteriorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.getResolucionAllMesAnteriorResponse> getResolucionAllMesAnteriorAsync() {
            Presentacion.ServiceReference1.getResolucionAllMesAnteriorRequest inValue = new Presentacion.ServiceReference1.getResolucionAllMesAnteriorRequest();
            return ((Presentacion.ServiceReference1.VHWService)(this)).getResolucionAllMesAnteriorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.AutenticateResponse Presentacion.ServiceReference1.VHWService.Autenticate(Presentacion.ServiceReference1.AutenticateRequest request) {
            return base.Channel.Autenticate(request);
        }
        
        public bool Autenticate(int rut, string password) {
            Presentacion.ServiceReference1.AutenticateRequest inValue = new Presentacion.ServiceReference1.AutenticateRequest();
            inValue.rut = rut;
            inValue.password = password;
            Presentacion.ServiceReference1.AutenticateResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).Autenticate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.AutenticateResponse> Presentacion.ServiceReference1.VHWService.AutenticateAsync(Presentacion.ServiceReference1.AutenticateRequest request) {
            return base.Channel.AutenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.AutenticateResponse> AutenticateAsync(int rut, string password) {
            Presentacion.ServiceReference1.AutenticateRequest inValue = new Presentacion.ServiceReference1.AutenticateRequest();
            inValue.rut = rut;
            inValue.password = password;
            return ((Presentacion.ServiceReference1.VHWService)(this)).AutenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.validateDocResponse Presentacion.ServiceReference1.VHWService.validateDoc(Presentacion.ServiceReference1.validateDocRequest request) {
            return base.Channel.validateDoc(request);
        }
        
        public bool validateDoc(string num) {
            Presentacion.ServiceReference1.validateDocRequest inValue = new Presentacion.ServiceReference1.validateDocRequest();
            inValue.num = num;
            Presentacion.ServiceReference1.validateDocResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).validateDoc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.validateDocResponse> Presentacion.ServiceReference1.VHWService.validateDocAsync(Presentacion.ServiceReference1.validateDocRequest request) {
            return base.Channel.validateDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.validateDocResponse> validateDocAsync(string num) {
            Presentacion.ServiceReference1.validateDocRequest inValue = new Presentacion.ServiceReference1.validateDocRequest();
            inValue.num = num;
            return ((Presentacion.ServiceReference1.VHWService)(this)).validateDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.getResolucionAllResponse Presentacion.ServiceReference1.VHWService.getResolucionAll(Presentacion.ServiceReference1.getResolucionAllRequest request) {
            return base.Channel.getResolucionAll(request);
        }
        
        public Presentacion.ServiceReference1.permisoUsuario[] getResolucionAll() {
            Presentacion.ServiceReference1.getResolucionAllRequest inValue = new Presentacion.ServiceReference1.getResolucionAllRequest();
            Presentacion.ServiceReference1.getResolucionAllResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).getResolucionAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getResolucionAllResponse> Presentacion.ServiceReference1.VHWService.getResolucionAllAsync(Presentacion.ServiceReference1.getResolucionAllRequest request) {
            return base.Channel.getResolucionAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.getResolucionAllResponse> getResolucionAllAsync() {
            Presentacion.ServiceReference1.getResolucionAllRequest inValue = new Presentacion.ServiceReference1.getResolucionAllRequest();
            return ((Presentacion.ServiceReference1.VHWService)(this)).getResolucionAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.getAntiguedadFunResponse Presentacion.ServiceReference1.VHWService.getAntiguedadFun(Presentacion.ServiceReference1.getAntiguedadFunRequest request) {
            return base.Channel.getAntiguedadFun(request);
        }
        
        public int getAntiguedadFun(int rutFun) {
            Presentacion.ServiceReference1.getAntiguedadFunRequest inValue = new Presentacion.ServiceReference1.getAntiguedadFunRequest();
            inValue.rutFun = rutFun;
            Presentacion.ServiceReference1.getAntiguedadFunResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).getAntiguedadFun(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getAntiguedadFunResponse> Presentacion.ServiceReference1.VHWService.getAntiguedadFunAsync(Presentacion.ServiceReference1.getAntiguedadFunRequest request) {
            return base.Channel.getAntiguedadFunAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.getAntiguedadFunResponse> getAntiguedadFunAsync(int rutFun) {
            Presentacion.ServiceReference1.getAntiguedadFunRequest inValue = new Presentacion.ServiceReference1.getAntiguedadFunRequest();
            inValue.rutFun = rutFun;
            return ((Presentacion.ServiceReference1.VHWService)(this)).getAntiguedadFunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.getAllByRutResponse Presentacion.ServiceReference1.VHWService.getAllByRut(Presentacion.ServiceReference1.getAllByRutRequest request) {
            return base.Channel.getAllByRut(request);
        }
        
        public Presentacion.ServiceReference1.permisoUsuario[] getAllByRut(int rut) {
            Presentacion.ServiceReference1.getAllByRutRequest inValue = new Presentacion.ServiceReference1.getAllByRutRequest();
            inValue.rut = rut;
            Presentacion.ServiceReference1.getAllByRutResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).getAllByRut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.getAllByRutResponse> Presentacion.ServiceReference1.VHWService.getAllByRutAsync(Presentacion.ServiceReference1.getAllByRutRequest request) {
            return base.Channel.getAllByRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.getAllByRutResponse> getAllByRutAsync(int rut) {
            Presentacion.ServiceReference1.getAllByRutRequest inValue = new Presentacion.ServiceReference1.getAllByRutRequest();
            inValue.rut = rut;
            return ((Presentacion.ServiceReference1.VHWService)(this)).getAllByRutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.lstCantidadPermisoEstadoResponse Presentacion.ServiceReference1.VHWService.lstCantidadPermisoEstado(Presentacion.ServiceReference1.lstCantidadPermisoEstadoRequest request) {
            return base.Channel.lstCantidadPermisoEstado(request);
        }
        
        public Presentacion.ServiceReference1.resumenCantidadPerEstado[] lstCantidadPermisoEstado() {
            Presentacion.ServiceReference1.lstCantidadPermisoEstadoRequest inValue = new Presentacion.ServiceReference1.lstCantidadPermisoEstadoRequest();
            Presentacion.ServiceReference1.lstCantidadPermisoEstadoResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).lstCantidadPermisoEstado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.lstCantidadPermisoEstadoResponse> Presentacion.ServiceReference1.VHWService.lstCantidadPermisoEstadoAsync(Presentacion.ServiceReference1.lstCantidadPermisoEstadoRequest request) {
            return base.Channel.lstCantidadPermisoEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.lstCantidadPermisoEstadoResponse> lstCantidadPermisoEstadoAsync() {
            Presentacion.ServiceReference1.lstCantidadPermisoEstadoRequest inValue = new Presentacion.ServiceReference1.lstCantidadPermisoEstadoRequest();
            return ((Presentacion.ServiceReference1.VHWService)(this)).lstCantidadPermisoEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadResponse Presentacion.ServiceReference1.VHWService.lstCantidadPermisoEstadoUnidad(Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadRequest request) {
            return base.Channel.lstCantidadPermisoEstadoUnidad(request);
        }
        
        public Presentacion.ServiceReference1.resumenCantidadPerEstado[] lstCantidadPermisoEstadoUnidad(string unidadInterna) {
            Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadRequest inValue = new Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadRequest();
            inValue.unidadInterna = unidadInterna;
            Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadResponse retVal = ((Presentacion.ServiceReference1.VHWService)(this)).lstCantidadPermisoEstadoUnidad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadResponse> Presentacion.ServiceReference1.VHWService.lstCantidadPermisoEstadoUnidadAsync(Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadRequest request) {
            return base.Channel.lstCantidadPermisoEstadoUnidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadResponse> lstCantidadPermisoEstadoUnidadAsync(string unidadInterna) {
            Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadRequest inValue = new Presentacion.ServiceReference1.lstCantidadPermisoEstadoUnidadRequest();
            inValue.unidadInterna = unidadInterna;
            return ((Presentacion.ServiceReference1.VHWService)(this)).lstCantidadPermisoEstadoUnidadAsync(inValue);
        }
    }
}
